### ISSUE TITLE
Add Topcoat CSS theme

### ISSUE THREAD

**Issue by TylerGauntlett** [TylerGauntlett/universal_convention#2]
Library: https://github.com/topcoat/topcoat

CDN: https://cdnjs.com/libraries/topcoat/

- [ ] Add add theming to page with Topcoat styles
- [ ] Style buttons
- [ ] Style background (dark theme)
- [ ] Style input textarea color to stand out from background

**Comment by bharati-21** [comment]
@TylerGauntlett Do I have to strictly use Topcoat CSS to style buttons or can I also use bootstrap?

**Comment by TylerGauntlett** [comment]
@bharati-21 I think ideally, it'd all be Topcoat for consistency

**Comment by bharati-21** [comment]
@TylerGauntlett yes, sure. It's just that there is already Bootstrap css used to style. Will keep this in mind

**Comment by TylerGauntlett** [comment]
@bharati-21 This issue would remove the existing Bootstrap styles in favor of Topcoat. Bootstrap can still be used for all page layout using `col` and `row`

**Comment by bharati-21** [comment]
Oh okay @TylerGauntlett! I thought you needed bootstrap styles as well! Thank you.

**Comment by TylerGauntlett** [comment]
@bharati-21 I started playing with this a bit ago. This is similar to what I'm envisioning

<img width="1091" alt="Screen Shot 2020-10-30 at 9 49 12 AM" src="https://user-images.githubusercontent.com/13861069/97712833-5e54d800-1a95-11eb-9336-486c85c17b35.png">

**Comment by bharati-21** [comment]
@TylerGauntlett  I have styled similar to the above picture you sent and tried adding more styles to the topcoat using CSS. I have created a PR for the same, and once you review and give your nod I will work on adding support for mobile phones. 
P.S. This is my first time with Topcoat CSS! Hope I did justice! Would love to hear back from you! Thank you.

**Comment by TylerGauntlett** [comment]
@bharati-21 see here https://github.com/TylerGauntlett/universal_convention/pull/10#issuecomment-719967723

**Comment by TylerGauntlett** [comment]
https://github.com/TylerGauntlett/universal_convention/pull/10 closed
